[template]
src = "etc/nginx/default.d/default.conf.tmpl"
dest = "/etc/nginx/default.d/default.conf"
keys = [
    "/nginx/listen/port",
    "/nginx/proxy/target",
    "/nginx/proxy/timeout/read",
    "/nginx/proxy/header",
    "/nginx/header",
    "/nginx/rewrite/permanent",
    "/nginx/rewrite/temporary"
]